ALTER TABLE cadastro.inscricoes alter column nome_bairro set data type character varying;
ALTER TABLE cadastro.inscricoes alter column nome_loteamento set data type character varying;
ALTER TABLE cadastro.inscricoes alter column quadra_loteamento set data type character varying;
ALTER TABLE cadastro.inscricoes  alter column lote_loteamento set data type character varying;
ALTER TABLE cadastro.inscricoes alter column natureza set data type character varying;
ALTER TABLE cadastro.inscricoes alter column nome_loteamento set data type character varying;
ALTER TABLE cadastro.inscricoes alter column tipo_lograd_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column nome_lograd_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column numero_lograd_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column complemento_lograd_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column bairro_lograd_end_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column cep_lograd_end_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column cidade_lograd_end_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column uf_lograd_end_contribuinte set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_patrimonio set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_posicao_fiscal set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_situacao_patri set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_adeq_para_ocupacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_situacao_do_lote set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_topografia set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_benfeitorias set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_passeio_para_ped set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_ocupacao_do_lote set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_pavimentacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_iluminacao_pub set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_rede_eletrica set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_rede_de_agua set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_rede_sanitaria set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_rede_tele set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_guia_e_sarjeta set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_coleta_lixo set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_galeria_pluvial set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_arvores_no_passeio set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_edificacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_tipo set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_atributos_espec set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_acabamento_ext set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_ter_imperm set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_sanitario set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_abast_agua set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_reserv_agua set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_estrutura set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_cobertura set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_tipo_de_unidade set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_class_arquit set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_acab_interno set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_inst_eletrica set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_inst_sanitaria set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_utilizacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_piso set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_forro set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_esquadrias set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_conservacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column descricao_situacao set data type character varying;
ALTER TABLE cadastro.inscricoes alter column nome_contribuinte_hash set data type character varying;
ALTER TABLE cadastro.inscricoes alter column cpf_hash set data type character varying;
ALTER TABLE cadastro.inscricoes alter column cnpj_hash set data type character varying;

ALTER TABLE cadastro.inscricoes alter column codigo_1 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_10 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_11 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_12 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_13 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_14 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_15 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_16 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_17 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_18 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_19 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_19_1 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_2 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_20 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_21 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_22 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_23 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_24 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_25 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_26 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_27 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_28 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_29 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_3 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_30 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_31 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_32 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_33 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_34 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_35 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_36 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_37 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_38 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_39 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_4 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_5 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_6 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_7 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_8 set data type int;
ALTER TABLE cadastro.inscricoes alter column codigo_9 set data type int;

ALTER TABLE cadastro.inscricoes alter column testada set data type numeric(15,2);
ALTER TABLE cadastro.inscricoes alter column area_lote set data type numeric(15,2);
ALTER TABLE cadastro.inscricoes alter column area_construida_unidade set data type numeric(15,2);
ALTER TABLE cadastro.inscricoes alter column area_construida_total set data type numeric(15,2);